# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24ab18548d3ab6e75f37227ae7c132a7392f1d7242107cd6bd2f7c07d805bea71a1786f522b33800504fe9f61be2f3b1cbd40d2c8a6663db15f540bfc4b888b3

test:
  secret_key_base: cf31a7933b948b27ea19c7fbd48b0ba26d7d9e691920a02fd012f0cfc82c56dd53ddd01547cf565c08bbb012d36e6b3855350a56dd8a942076bba50653ee04c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
